import Link from "next/link";
import Script from "next/script";

import { getEnvironment } from "@/server/env";

const messages: Readonly<Record<string, string>> = {
    invalid: "Enter a valid email address and password.", invalid_credentials: "The email or password is incorrect.", email_unverified: "Verify your email address before signing in.", account_scheduled_for_deletion: "This account is scheduled for deletion.", session_configuration_missing: "Browser sessions are not configured.", rate_limited: "Too many sign-in attempts. Try again in a minute.", turnstile: "Complete the security check and try again.", oauth_configuration: "That login provider is not configured.", oauth_state: "That provider login expired. Please try again.", oauth_denied: "Provider login was cancelled.", oauth_failed: "The provider could not sign you in.",
};

const LoginPage = async ({ searchParams }: { searchParams: Promise<{ error?: string; next?: string; deletion?: string }> }) => {
    const parameters = await searchParams;
    const environment = getEnvironment();
    const error = parameters.error === undefined ? undefined : messages[parameters.error];
    return <main className="auth-page"><section className="auth-intro"><Link href="/" className="wordmark">Relaticle</Link><p className="eyebrow">Workspace CRM</p><h1>Pick up the conversation where your team left it.</h1><p>Relationships, work, and context stay connected in one focused workspace.</p></section><section className="auth-card" aria-labelledby="login-heading"><p className="eyebrow">Welcome back</p><h2 id="login-heading">Sign in</h2>{parameters.deletion === "scheduled" ? <p role="status">Deletion scheduled. Check your email for confirmation.</p> : null}{error ? <p className="form-error" role="alert">{error}</p> : null}<div className="social-auth">{environment.GITHUB_CLIENT_ID ? <Link className="social-button" href={`/auth/oauth/github?next=${encodeURIComponent(parameters.next ?? "")}`}>Continue with GitHub</Link> : null}{environment.GOOGLE_CLIENT_ID ? <Link className="social-button" href={`/auth/oauth/google?next=${encodeURIComponent(parameters.next ?? "")}`}>Continue with Google</Link> : null}</div>{environment.GITHUB_CLIENT_ID || environment.GOOGLE_CLIENT_ID ? <p className="auth-divider"><span>or use email</span></p> : null}<form method="post" action="/auth/login"><input type="hidden" name="next" value={parameters.next ?? ""} /><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="email" required /><label htmlFor="password">Password</label><input id="password" name="password" type="password" autoComplete="current-password" required /><label className="check-row"><input name="remember" type="checkbox" /> Keep me signed in</label>{environment.TURNSTILE_SITE_KEY ? <div className="cf-turnstile" data-sitekey={environment.TURNSTILE_SITE_KEY} /> : null}<button type="submit">Sign in to workspace</button></form><div className="auth-links"><Link href="/app/password-reset/request">Forgot password?</Link><Link href="/app/register">Create account</Link></div>{environment.TURNSTILE_SITE_KEY ? <Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive" /> : null}</section></main>;
};
export default LoginPage;
