"use client";

import { useActionState } from "react";

import { customFieldEntityTypes, customFieldTypes } from "@/server/custom-fields/types";
import type { FieldSettingsState } from "@/app/app/[teamSlug]/settings/custom-fields/actions";

import styles from "./crm.module.css";

type Section = Readonly<{ id: string; name: string; entityType: string; active: boolean; systemDefined: boolean }>;
type Field = Readonly<{ id: string; sectionId: string | null; name: string; code: string; type: string; entityType: string; active: boolean; systemDefined: boolean; required: boolean; minimum: string; maximum: string; options: readonly string[] }>;
type Action = (state: FieldSettingsState, data: FormData) => Promise<FieldSettingsState>;
type FormAction = (data: FormData) => void;
const initial: FieldSettingsState = { status: "idle", message: "" };

const Reorder = ({ action, id, kind }: { action: FormAction; id: string; kind: "section" | "field" | "option" }) => <div className={styles.reorder}><form action={action}><input type="hidden" name="intent" value="reorder" /><input type="hidden" name="kind" value={kind} /><input type="hidden" name="id" value={id} /><input type="hidden" name="direction" value="up" /><button type="submit" aria-label="Move up">↑</button></form><form action={action}><input type="hidden" name="intent" value="reorder" /><input type="hidden" name="kind" value={kind} /><input type="hidden" name="id" value={id} /><input type="hidden" name="direction" value="down" /><button type="submit" aria-label="Move down">↓</button></form></div>;

const FieldForm = ({ action, field, sections }: { action: FormAction; field?: Field; sections: readonly Section[] }) => <details className={styles.fieldEditor} open={field === undefined}><summary>{field?.name ?? "Add a field"}</summary><form action={action} className={styles.settingsForm}><input type="hidden" name="intent" value="field" /><input type="hidden" name="id" value={field?.id ?? ""} /><label>Name<input name="name" required defaultValue={field?.name} /></label><label>Code<input name="code" defaultValue={field?.code} placeholder="generated_from_name" /></label><label>Record type<select name="entity_type" defaultValue={field?.entityType ?? "company"}>{customFieldEntityTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>Input type<select name="type" defaultValue={field?.type ?? "text"}>{customFieldTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>Section<select name="section_id" defaultValue={field?.sectionId ?? ""}><option value="">No section</option>{sections.map((section) => <option key={section.id} value={section.id}>{section.entityType}: {section.name}</option>)}</select></label><label className={styles.checkboxLabel}><input type="checkbox" name="required" value="true" defaultChecked={field?.required} /> Required</label><label>Minimum<input name="minimum" type="number" defaultValue={field?.minimum} /></label><label>Maximum<input name="maximum" type="number" defaultValue={field?.maximum} /></label><label className={styles.wideField}>Options, one per line<textarea name="options" defaultValue={field?.options.join("\n")} /></label><button type="submit">Save field</button></form></details>;

export const CustomFieldManager = ({ action, canManage, fields, sections }: Readonly<{ action: Action; canManage: boolean; fields: readonly Field[]; sections: readonly Section[] }>) => {
    const [state, formAction] = useActionState(action, initial);
    if (!canManage) return <section className={styles.panel}><h2>Administrator access required</h2><p>Only workspace owners and administrators can change field definitions.</p></section>;
    return <><section className={styles.panel}><h2>Sections</h2><form action={formAction} className={styles.inlineSettings}><input type="hidden" name="intent" value="section" /><input name="name" aria-label="Section name" placeholder="Section name" required /><select name="entity_type" aria-label="Section record type">{customFieldEntityTypes.map((type) => <option key={type}>{type}</option>)}</select><button type="submit">Add section</button></form><ul className={styles.settingsList}>{sections.map((section) => <li key={section.id}><form action={formAction} className={styles.inlineSettings}><input type="hidden" name="intent" value="section" /><input type="hidden" name="id" value={section.id} /><input name="name" aria-label={`Name for ${section.name}`} defaultValue={section.name} required /><select name="entity_type" aria-label={`Record type for ${section.name}`} defaultValue={section.entityType}>{customFieldEntityTypes.map((type) => <option key={type}>{type}</option>)}</select><button type="submit">Save</button></form><Reorder action={formAction} id={section.id} kind="section" />{!section.systemDefined ? <form action={formAction}><input type="hidden" name="intent" value="section-active" /><input type="hidden" name="id" value={section.id} /><input type="hidden" name="active" value={section.active ? "false" : "true"} /><button type="submit">{section.active ? "Disable" : "Enable"}</button></form> : null}</li>)}</ul></section><section className={styles.panel}><h2>Field definitions</h2><FieldForm action={formAction} sections={sections} />{fields.map((field) => <div className={styles.fieldManagerRow} key={field.id}><FieldForm action={formAction} field={field} sections={sections} /><Reorder action={formAction} id={field.id} kind="field" />{!field.systemDefined ? <form action={formAction}><input type="hidden" name="intent" value="active" /><input type="hidden" name="id" value={field.id} /><input type="hidden" name="active" value={field.active ? "false" : "true"} /><button type="submit">{field.active ? "Disable" : "Enable"}</button></form> : null}</div>)}<p role="status" className={state.status === "error" ? styles.error : styles.success}>{state.message}</p></section></>;
};
