import Link from "next/link";
import Script from "next/script";

import { getEnvironment } from "@/server/env";

const messages: Record<string, string> = { invalid: "Complete every field and use a password of at least 12 characters.", exists: "An account already uses that email address.", failed: "The account could not be created.", turnstile: "Complete the security check and try again." };
const RegisterPage = async ({ searchParams }: { searchParams: Promise<{ error?: string }> }) => {
    const { error } = await searchParams;
    const environment = getEnvironment();
    return <main className="auth-page"><section className="auth-intro"><Link href="/" className="wordmark">Relaticle</Link><p className="eyebrow">Start together</p><h1>Give every relationship a shared home.</h1><p>Create your account, then shape a workspace around how your team works.</p></section><section className="auth-card"><p className="eyebrow">New account</p><h2>Create account</h2>{error ? <p className="form-error" role="alert">{messages[error] ?? messages.failed}</p> : null}<div className="social-auth">{environment.GITHUB_CLIENT_ID ? <Link className="social-button" href="/auth/oauth/github">Sign up with GitHub</Link> : null}{environment.GOOGLE_CLIENT_ID ? <Link className="social-button" href="/auth/oauth/google">Sign up with Google</Link> : null}</div>{environment.GITHUB_CLIENT_ID || environment.GOOGLE_CLIENT_ID ? <p className="auth-divider"><span>or use email</span></p> : null}<form method="post" action="/auth/register"><label htmlFor="name">Name</label><input id="name" name="name" autoComplete="name" required /><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="email" required /><label htmlFor="password">Password</label><input id="password" name="password" type="password" minLength={12} autoComplete="new-password" required /><label htmlFor="password_confirmation">Confirm password</label><input id="password_confirmation" name="password_confirmation" type="password" minLength={12} autoComplete="new-password" required />{environment.TURNSTILE_SITE_KEY ? <div className="cf-turnstile" data-sitekey={environment.TURNSTILE_SITE_KEY} /> : null}<button type="submit">Create account</button></form><div className="auth-links"><Link href="/app/login">Already have an account?</Link></div>{environment.TURNSTILE_SITE_KEY ? <Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive" /> : null}</section></main>;
};
export default RegisterPage;
