import Link from "next/link";

import { requireBrowserTeam } from "@/server/auth/browser/context";
import { listTeam } from "@/server/workspaces/service";

const TeamSettingsPage = async ({ params, searchParams }: { params: Promise<{ teamSlug: string }>; searchParams: Promise<{ updated?: string; error?: string }> }) => {
    const { teamSlug } = await params;
    const auth = await requireBrowserTeam(teamSlug);
    const team = await listTeam(auth.context.userId, auth.context.teamId);
    const state = await searchParams;
    return <main className="account-page"><nav className="account-nav"><Link href={`/app/${teamSlug}`} className="wordmark">Relaticle</Link><Link href={`/app/${teamSlug}`}>Workspace</Link><Link href="/app/new">Switch workspace</Link><Link href="/app/settings/profile">Account</Link></nav><section className="account-content"><p className="eyebrow">{auth.team.name}</p><h1>Team settings</h1>{state.updated === "1" ? <p role="status">Team updated.</p> : null}{state.error === undefined ? null : <p className="form-error">The team could not be updated.</p>}{team.canManage ? <div className="account-grid"><article className="account-panel"><h2>Invite a member</h2><form className="stack-form" method="post" action="/auth/team"><input type="hidden" name="team_slug" value={teamSlug} /><input type="hidden" name="intent" value="invite" /><label htmlFor="email">Email address</label><input id="email" name="email" type="email" required /><label htmlFor="role">Role</label><select id="role" name="role"><option value="member">Member</option><option value="admin">Administrator</option></select><button type="submit">Send invitation</button></form><h3>Pending invitations</h3>{team.invitations.map((invitation) => <p key={invitation.id}>{invitation.email} ({invitation.role})</p>)}</article><article className="account-panel"><h2>Members</h2>{team.members.map((member) => <div className="member-row" key={member.id}><span><strong>{member.name}</strong><small>{member.email}</small></span><form method="post" action="/auth/team"><input type="hidden" name="team_slug" value={teamSlug} /><input type="hidden" name="member_id" value={member.id} /><select name="role" defaultValue={member.role ?? "member"}><option value="member">Member</option><option value="admin">Administrator</option></select><button name="intent" value="role">Update</button><button name="intent" value="remove">Remove</button></form></div>)}</article></div> : <p>You are a member of this workspace. Administrator access is required to manage the team.</p>}<form method="post" action="/auth/team"><input type="hidden" name="team_slug" value={teamSlug} /><input type="hidden" name="intent" value="leave" /><button className="danger-button" type="submit">Leave workspace</button></form></section></main>;
};
export default TeamSettingsPage;
